// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMS.Infrastructure.Data;

#nullable disable

namespace SMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250112180001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMS.Core.Entities.FamilyMember", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelationshipId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("FamilyMembers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateOfBirth = new DateTime(1975, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Harry",
                            LastName = "Joe",
                            RelationshipId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            ID = 2,
                            DateOfBirth = new DateTime(1983, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jack",
                            LastName = "Connor",
                            RelationshipId = 2,
                            StudentId = 2
                        },
                        new
                        {
                            ID = 3,
                            DateOfBirth = new DateTime(2013, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Smith",
                            LastName = "Roberts",
                            RelationshipId = 3,
                            StudentId = 6
                        },
                        new
                        {
                            ID = 4,
                            DateOfBirth = new DateTime(1898, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "George",
                            LastName = "Rhys",
                            RelationshipId = 3,
                            StudentId = 4
                        },
                        new
                        {
                            ID = 5,
                            DateOfBirth = new DateTime(2020, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alexander",
                            LastName = "Joseph",
                            RelationshipId = 1,
                            StudentId = 5
                        },
                        new
                        {
                            ID = 6,
                            DateOfBirth = new DateTime(2017, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "William",
                            LastName = "Damian",
                            RelationshipId = 2,
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("SMS.Core.Entities.FamilyMemberNationality", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("FamilyMemberId")
                        .HasColumnType("int");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("FamilyMemberNationalities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FamilyMemberId = 1,
                            NationalityId = 1
                        },
                        new
                        {
                            ID = 2,
                            FamilyMemberId = 2,
                            NationalityId = 5
                        },
                        new
                        {
                            ID = 3,
                            FamilyMemberId = 3,
                            NationalityId = 97
                        },
                        new
                        {
                            ID = 4,
                            FamilyMemberId = 4,
                            NationalityId = 40
                        },
                        new
                        {
                            ID = 5,
                            FamilyMemberId = 5,
                            NationalityId = 9
                        },
                        new
                        {
                            ID = 6,
                            FamilyMemberId = 6,
                            NationalityId = 77
                        });
                });

            modelBuilder.Entity("SMS.Core.Entities.Nationality", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Code = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            ID = 2,
                            Code = "AX",
                            Name = "land Islands"
                        },
                        new
                        {
                            ID = 3,
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            ID = 4,
                            Code = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            ID = 5,
                            Code = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            ID = 6,
                            Code = "AD",
                            Name = "AndorrA"
                        },
                        new
                        {
                            ID = 7,
                            Code = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            ID = 8,
                            Code = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            ID = 9,
                            Code = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            ID = 10,
                            Code = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            ID = 11,
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            ID = 12,
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            ID = 13,
                            Code = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            ID = 14,
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            ID = 15,
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            ID = 16,
                            Code = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            ID = 17,
                            Code = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            ID = 18,
                            Code = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            ID = 19,
                            Code = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            ID = 20,
                            Code = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            ID = 21,
                            Code = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            ID = 22,
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            ID = 23,
                            Code = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            ID = 24,
                            Code = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            ID = 25,
                            Code = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            ID = 26,
                            Code = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            ID = 27,
                            Code = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            ID = 28,
                            Code = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            ID = 29,
                            Code = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            ID = 30,
                            Code = "BV",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            ID = 31,
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            ID = 32,
                            Code = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            ID = 33,
                            Code = "BN",
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            ID = 34,
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            ID = 35,
                            Code = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            ID = 36,
                            Code = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            ID = 37,
                            Code = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            ID = 38,
                            Code = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            ID = 39,
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            ID = 40,
                            Code = "CV",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            ID = 41,
                            Code = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            ID = 42,
                            Code = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            ID = 43,
                            Code = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            ID = 44,
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            ID = 45,
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            ID = 46,
                            Code = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            ID = 47,
                            Code = "CC",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            ID = 48,
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            ID = 49,
                            Code = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            ID = 50,
                            Code = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            ID = 51,
                            Code = "CD",
                            Name = "Congo, The Democratic Republic of the"
                        },
                        new
                        {
                            ID = 52,
                            Code = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            ID = 53,
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            ID = 54,
                            Code = "CI",
                            Name = "Cote D\"Ivoire"
                        },
                        new
                        {
                            ID = 55,
                            Code = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            ID = 56,
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            ID = 57,
                            Code = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            ID = 58,
                            Code = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            ID = 59,
                            Code = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            ID = 60,
                            Code = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            ID = 61,
                            Code = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            ID = 62,
                            Code = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            ID = 63,
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            ID = 64,
                            Code = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            ID = 65,
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            ID = 66,
                            Code = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            ID = 67,
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            ID = 68,
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            ID = 69,
                            Code = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            ID = 70,
                            Code = "FK",
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            ID = 71,
                            Code = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            ID = 72,
                            Code = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            ID = 73,
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            ID = 74,
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            ID = 75,
                            Code = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            ID = 76,
                            Code = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            ID = 77,
                            Code = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            ID = 78,
                            Code = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            ID = 79,
                            Code = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            ID = 80,
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            ID = 81,
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            ID = 82,
                            Code = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            ID = 83,
                            Code = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            ID = 84,
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            ID = 85,
                            Code = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            ID = 86,
                            Code = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            ID = 87,
                            Code = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            ID = 88,
                            Code = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            ID = 89,
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            ID = 90,
                            Code = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            ID = 91,
                            Code = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            ID = 92,
                            Code = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            ID = 93,
                            Code = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            ID = 94,
                            Code = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            ID = 95,
                            Code = "HM",
                            Name = "Heard Island and Mcdonald Islands"
                        },
                        new
                        {
                            ID = 96,
                            Code = "VA",
                            Name = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            ID = 97,
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            ID = 98,
                            Code = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            ID = 99,
                            Code = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            ID = 100,
                            Code = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            ID = 101,
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            ID = 102,
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            ID = 103,
                            Code = "IR",
                            Name = "Iran, Islamic Republic Of"
                        },
                        new
                        {
                            ID = 104,
                            Code = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            ID = 105,
                            Code = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            ID = 106,
                            Code = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            ID = 107,
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            ID = 108,
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            ID = 109,
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            ID = 110,
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            ID = 111,
                            Code = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            ID = 112,
                            Code = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            ID = 113,
                            Code = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            ID = 114,
                            Code = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            ID = 115,
                            Code = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            ID = 116,
                            Code = "KP",
                            Name = "Korea, Democratic People\"S Republic of"
                        },
                        new
                        {
                            ID = 117,
                            Code = "KR",
                            Name = "Korea, Republic of"
                        },
                        new
                        {
                            ID = 118,
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            ID = 119,
                            Code = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            ID = 120,
                            Code = "LA",
                            Name = "Lao People\"S Democratic Republic"
                        },
                        new
                        {
                            ID = 121,
                            Code = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            ID = 122,
                            Code = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            ID = 123,
                            Code = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            ID = 124,
                            Code = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            ID = 125,
                            Code = "LY",
                            Name = "Libyan Arab Jamahiriya"
                        },
                        new
                        {
                            ID = 126,
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            ID = 127,
                            Code = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            ID = 128,
                            Code = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            ID = 129,
                            Code = "MO",
                            Name = "Macao"
                        },
                        new
                        {
                            ID = 130,
                            Code = "MK",
                            Name = "Macedonia, The Former Yugoslav Republic of"
                        },
                        new
                        {
                            ID = 131,
                            Code = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            ID = 132,
                            Code = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            ID = 133,
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            ID = 134,
                            Code = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            ID = 135,
                            Code = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            ID = 136,
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            ID = 137,
                            Code = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            ID = 138,
                            Code = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            ID = 139,
                            Code = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            ID = 140,
                            Code = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            ID = 141,
                            Code = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            ID = 142,
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            ID = 143,
                            Code = "FM",
                            Name = "Micronesia, Federated States of"
                        },
                        new
                        {
                            ID = 144,
                            Code = "MD",
                            Name = "Moldova, Republic of"
                        },
                        new
                        {
                            ID = 145,
                            Code = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            ID = 146,
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            ID = 147,
                            Code = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            ID = 148,
                            Code = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            ID = 149,
                            Code = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            ID = 150,
                            Code = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            ID = 151,
                            Code = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            ID = 152,
                            Code = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            ID = 153,
                            Code = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            ID = 154,
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            ID = 155,
                            Code = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            ID = 156,
                            Code = "AN",
                            Name = "Netherlands Antilles"
                        },
                        new
                        {
                            ID = 157,
                            Code = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            ID = 158,
                            Code = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            ID = 159,
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            ID = 160,
                            Code = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            ID = 161,
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            ID = 162,
                            Code = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            ID = 163,
                            Code = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            ID = 164,
                            Code = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            ID = 165,
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            ID = 166,
                            Code = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            ID = 167,
                            Code = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            ID = 168,
                            Code = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            ID = 169,
                            Code = "PS",
                            Name = "Palestinian Territory, Occupied"
                        },
                        new
                        {
                            ID = 170,
                            Code = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            ID = 171,
                            Code = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            ID = 172,
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            ID = 173,
                            Code = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            ID = 174,
                            Code = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            ID = 175,
                            Code = "PN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            ID = 176,
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            ID = 177,
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            ID = 178,
                            Code = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            ID = 179,
                            Code = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            ID = 180,
                            Code = "RE",
                            Name = "Reunion"
                        },
                        new
                        {
                            ID = 181,
                            Code = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            ID = 182,
                            Code = "RU",
                            Name = "Russian Federation"
                        },
                        new
                        {
                            ID = 183,
                            Code = "RW",
                            Name = "RWANDA"
                        },
                        new
                        {
                            ID = 184,
                            Code = "SH",
                            Name = "Saint Helena"
                        },
                        new
                        {
                            ID = 185,
                            Code = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            ID = 186,
                            Code = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            ID = 187,
                            Code = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            ID = 188,
                            Code = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            ID = 189,
                            Code = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            ID = 190,
                            Code = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            ID = 191,
                            Code = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            ID = 192,
                            Code = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            ID = 193,
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            ID = 194,
                            Code = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            ID = 195,
                            Code = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            ID = 196,
                            Code = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            ID = 197,
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            ID = 198,
                            Code = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            ID = 199,
                            Code = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            ID = 200,
                            Code = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            ID = 201,
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            ID = 202,
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            ID = 203,
                            Code = "GS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            ID = 204,
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            ID = 205,
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            ID = 206,
                            Code = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            ID = 207,
                            Code = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            ID = 208,
                            Code = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            ID = 209,
                            Code = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            ID = 210,
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            ID = 211,
                            Code = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            ID = 212,
                            Code = "SY",
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            ID = 213,
                            Code = "TW",
                            Name = "Taiwan, Province of China"
                        },
                        new
                        {
                            ID = 214,
                            Code = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            ID = 215,
                            Code = "TZ",
                            Name = "Tanzania, United Republic of"
                        },
                        new
                        {
                            ID = 216,
                            Code = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            ID = 217,
                            Code = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            ID = 218,
                            Code = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            ID = 219,
                            Code = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            ID = 220,
                            Code = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            ID = 221,
                            Code = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            ID = 222,
                            Code = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            ID = 223,
                            Code = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            ID = 224,
                            Code = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            ID = 225,
                            Code = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            ID = 226,
                            Code = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            ID = 227,
                            Code = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            ID = 228,
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            ID = 229,
                            Code = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            ID = 230,
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            ID = 231,
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            ID = 232,
                            Code = "UM",
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            ID = 233,
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            ID = 234,
                            Code = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            ID = 235,
                            Code = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            ID = 236,
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            ID = 237,
                            Code = "VN",
                            Name = "Viet Nam"
                        },
                        new
                        {
                            ID = 238,
                            Code = "VG",
                            Name = "Virgin Islands, British"
                        },
                        new
                        {
                            ID = 239,
                            Code = "VI",
                            Name = "Virgin Islands, U.S."
                        },
                        new
                        {
                            ID = 240,
                            Code = "WF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            ID = 241,
                            Code = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            ID = 242,
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            ID = 243,
                            Code = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            ID = 244,
                            Code = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("SMS.Core.Entities.Relationship", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Relationships");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Parent"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Sibling"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Spouse"
                        });
                });

            modelBuilder.Entity("SMS.Core.Entities.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateOfBirth = new DateTime(2000, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Doe",
                            Status = "Active"
                        },
                        new
                        {
                            ID = 2,
                            DateOfBirth = new DateTime(1983, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Smith",
                            Status = "Active"
                        },
                        new
                        {
                            ID = 3,
                            DateOfBirth = new DateTime(2010, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Leanne",
                            LastName = "Graham",
                            Status = "Active"
                        },
                        new
                        {
                            ID = 4,
                            DateOfBirth = new DateTime(1798, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dennis",
                            LastName = "Schulist",
                            Status = "Active"
                        },
                        new
                        {
                            ID = 5,
                            DateOfBirth = new DateTime(2000, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Glenna",
                            LastName = "Reichert",
                            Status = "Active"
                        },
                        new
                        {
                            ID = 6,
                            DateOfBirth = new DateTime(2004, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ervin",
                            LastName = "Howell",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("SMS.Core.Entities.StudentNationality", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("StudentNationalities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            NationalityId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            ID = 2,
                            NationalityId = 5,
                            StudentId = 2
                        },
                        new
                        {
                            ID = 3,
                            NationalityId = 97,
                            StudentId = 3
                        },
                        new
                        {
                            ID = 4,
                            NationalityId = 40,
                            StudentId = 4
                        },
                        new
                        {
                            ID = 5,
                            NationalityId = 9,
                            StudentId = 5
                        },
                        new
                        {
                            ID = 6,
                            NationalityId = 77,
                            StudentId = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
